import { useEffect, useState } from 'react';
import { api } from '../api';
import { Badge, Empty, ErrorNotice, Field, JsonView, Panel, SuccessNotice, statusTone, type PageProps } from '../components/Primitives';
import type { GitState } from '../types';

export function GitPage({ projectId, snapshot, refresh }: PageProps) {
  const [git, setGit] = useState<GitState | null>(null); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  const [preview, setPreview] = useState('{\n  "git_action_id": "git-ui",\n  "room_id": "",\n  "revision_id": "",\n  "node_id": "",\n  "operation": "create_worktree",\n  "repository_root": "",\n  "source_ref": "main",\n  "new_branch": "task/example",\n  "worktree_path": ""\n}');
  const [approvalId, setApprovalId] = useState('git-approval-ui'); const [actionId, setActionId] = useState('git-ui');
  async function load() { try { setGit(await api.git(projectId)); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } }
  useEffect(() => { void load(); }, [projectId]);
  async function act(label: string, action: string, body: unknown) { setError(null); setSuccess(null); try { await api.action(projectId, action, typeof body === 'function' ? body() : body); setSuccess(`${label}已提交。`); await Promise.all([refresh(), load()]); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } }
  return <div className="page-grid"><ErrorNotice error={error} /><SuccessNotice message={success} />
    <Panel title="当前 Git" className="span-all" aside={<button onClick={() => void load()}>刷新 Git</button>}>
      {!git ? <Empty>正在读取 Git 状态…</Empty> : <><div className="meta-grid"><span>Branch<strong>{git.branch ?? 'detached'}</strong></span><span>Changes<strong>{git.status.length}</strong></span><span>Worktrees<strong>{git.worktrees.length}</strong></span></div>{git.status.length > 0 && <pre className="git-status">{git.status.join('\n')}</pre>}<div className="worktree-grid">{git.worktrees.map((worktree) => <div className="worktree" key={worktree.path}><strong>{worktree.branch ?? 'detached'}</strong><span>{worktree.path}</span><small>{worktree.head ?? '—'}</small></div>)}</div></>}
    </Panel>
    <Panel title="GitAction preview" className="span-2"><p className="muted">Preview 只允许三种 typed operation；execute 只能由 `GitController` 处理。</p><Field label="Advanced JSON：typed preview"><textarea className="code-input x-tall" value={preview} onChange={(e) => setPreview(e.target.value)} /></Field><button className="primary" onClick={() => void act('Git preview', 'git-preview', () => { const body = JSON.parse(preview) as Record<string, unknown>; if (!body.room_id) body.room_id = snapshot.room.room_id; return body; })}>创建 preview</button></Panel>
    <Panel title="审批与执行"><Field label="GitAction ID"><input value={actionId} onChange={(e) => setActionId(e.target.value)} /></Field><Field label="Approval ID"><input value={approvalId} onChange={(e) => setApprovalId(e.target.value)} /></Field><div className="button-column"><button className="primary" onClick={() => void act('Git approval', 'decide-git-action', { approval_id: approvalId, git_action_id: actionId, decision: 'approved', confirmed_by_user: true })}>明确批准 preview</button><button onClick={() => void act('Git rejection', 'decide-git-action', { approval_id: approvalId, git_action_id: actionId, decision: 'rejected', confirmed_by_user: true })}>拒绝 preview</button><button className="danger" onClick={() => void act('Git execute', 'git-execute', { git_action_id: actionId })}>执行已批准 Action</button><button onClick={() => void act('Git reconcile', 'git-reconcile', { git_action_id: actionId })}>标记 outcome unknown</button></div></Panel>
    <Panel title="Durable GitActions" className="span-all">{snapshot.git_actions.length === 0 ? <Empty>没有 GitAction。</Empty> : <div className="list">{snapshot.git_actions.map((action) => <details key={String(action.git_action_id)}><summary><strong>{String(action.git_action_id)}</strong> · {String(action.operation)} <Badge tone={statusTone(action.status)}>{String(action.status)}</Badge></summary><JsonView value={action} /></details>)}</div>}</Panel>
  </div>;
}
