import { useState } from 'react';
import { api } from '../api';
import { Badge, Empty, ErrorNotice, Field, JsonView, Panel, SuccessNotice, statusTone, type PageProps } from '../components/Primitives';

const findingExample = '[\n  {\n    "finding_id": "finding-1",\n    "severity": "high",\n    "title": "",\n    "file": "",\n    "line": null,\n    "trigger": "",\n    "evidence": "",\n    "impact": "",\n    "requirement_relation": "",\n    "minimal_direction": ""\n  }\n]';

export function ReviewsPage({ projectId, snapshot, refresh }: PageProps) {
  const reviewable = snapshot.runs.find((run) => run.status === 'review_required');
  const workItem = snapshot.run_work_items.find((item) => item.run_id === reviewable?.run_id);
  const [form, setForm] = useState({ reviewId: 'review-ui', runId: reviewable?.run_id ?? '', taskId: workItem?.current_task_id ?? '', attemptId: workItem?.current_attempt_id ?? '', decision: 'approved', summary: '' });
  const [findings, setFindings] = useState('[]');
  const [fixPrimary, setFixPrimary] = useState({ taskId: 'fix-ui', runId: '', parentTaskId: '', reviewId: '', goal: '' });
  const [fixJson, setFixJson] = useState('{\n  "task_id": "fix-ui",\n  "room_id": "",\n  "run_id": "",\n  "type": "fix",\n  "parent_task_id": "",\n  "based_on_review_id": "",\n  "background": "",\n  "goal": "",\n  "requirements": [],\n  "non_goals": [],\n  "architecture_decisions": [],\n  "scope": ["review_fixes_only"],\n  "constraints": [],\n  "acceptance_criteria": [],\n  "verification": [],\n  "documentation_updates": [],\n  "question_policy": "ask only if scope changes",\n  "confirmed_by_user": true,\n  "created_by": "codex",\n  "created_at": "",\n  "confirmed_findings": []\n}');
  const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  async function act(label: string, action: string, body: unknown) { setError(null); setSuccess(null); try { await api.action(projectId, action, body); setSuccess(`${label}已提交。`); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } }

  return <div className="page-grid"><ErrorNotice error={error} /><SuccessNotice message={success} />
    <Panel title="提交 Review" className="span-2"><form onSubmit={(event) => { event.preventDefault(); void act('Review', 'submit-review', { review_id: form.reviewId, run_id: form.runId, task_id: form.taskId, attempt_id: form.attemptId, decision: form.decision, findings: JSON.parse(findings), open_questions: [], verification_summary: form.summary }); }}>
      <div className="form-grid"><Field label="Review ID"><input value={form.reviewId} onChange={(e) => setForm({ ...form, reviewId: e.target.value })} /></Field><Field label="Decision"><select value={form.decision} onChange={(e) => setForm({ ...form, decision: e.target.value })}><option>approved</option><option>changes_requested</option><option>needs_discussion</option></select></Field><Field label="Run ID"><input value={form.runId} onChange={(e) => setForm({ ...form, runId: e.target.value })} /></Field><Field label="Task ID"><input value={form.taskId} onChange={(e) => setForm({ ...form, taskId: e.target.value })} /></Field><Field label="Attempt ID"><input value={form.attemptId} onChange={(e) => setForm({ ...form, attemptId: e.target.value })} /></Field><Field label="Verification summary"><input value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} /></Field></div>
      <Field label="Advanced JSON：findings" hint="实现正确时必须使用空数组 []。"><textarea className="code-input tall" value={findings} onChange={(e) => setFindings(e.target.value)} placeholder={findingExample} /></Field><button className="primary" type="submit">提交 Review</button>
    </form></Panel>
    <Panel title="Review 记录">{snapshot.reviews.length === 0 ? <Empty>没有 Review。</Empty> : <div className="list">{snapshot.reviews.map((review) => <div className="list-row column" key={String(review.review_id)}><div className="row-between"><strong>{String(review.review_id)}</strong><Badge tone={statusTone(review.decision)}>{String(review.decision)}</Badge></div><p>{String(review.verification_summary || '')}</p>{((review.findings as Array<Record<string, unknown>> | undefined) ?? []).map((finding) => <div className="finding" key={String(finding.finding_id)}><Badge tone="bad">{String(finding.severity)}</Badge><strong>{String(finding.title)}</strong><p>{String(finding.impact)}</p></div>)}<div className="button-row"><button className="primary" disabled={review.decision !== 'approved'} title={review.decision === 'approved' ? '' : '只有 approved Review 可接受'} onClick={() => void act('Review acceptance', 'accept-review', { review_id: review.review_id, confirmed_by_user: true })}>明确接受</button></div></div>)}</div>}</Panel>
    <Panel title="准备并提交 Fix Task" className="span-all"><p className="muted">只接受完整 `type=fix` Contract；必须引用当前 Review 与 confirmed findings，不会隐式批准。</p><div className="form-grid"><Field label="Task ID"><input value={fixPrimary.taskId} onChange={(e) => setFixPrimary({ ...fixPrimary, taskId: e.target.value })} /></Field><Field label="Run ID"><input value={fixPrimary.runId} onChange={(e) => setFixPrimary({ ...fixPrimary, runId: e.target.value })} /></Field><Field label="Parent Task ID"><input value={fixPrimary.parentTaskId} onChange={(e) => setFixPrimary({ ...fixPrimary, parentTaskId: e.target.value })} /></Field><Field label="Based on Review ID"><input value={fixPrimary.reviewId} onChange={(e) => setFixPrimary({ ...fixPrimary, reviewId: e.target.value })} /></Field><Field label="Goal"><input value={fixPrimary.goal} onChange={(e) => setFixPrimary({ ...fixPrimary, goal: e.target.value })} /></Field></div><Field label="Advanced JSON：完整 Fix Task Contract"><textarea className="code-input x-tall" value={fixJson} onChange={(e) => setFixJson(e.target.value)} /></Field><button className="primary" onClick={() => { const parsed = JSON.parse(fixJson) as Record<string, unknown>; Object.assign(parsed, { task_id: fixPrimary.taskId, run_id: fixPrimary.runId, parent_task_id: fixPrimary.parentTaskId, based_on_review_id: fixPrimary.reviewId, goal: fixPrimary.goal }); if (!parsed.room_id) parsed.room_id = snapshot.room.room_id; if (!parsed.created_at) parsed.created_at = new Date().toISOString(); void act('Fix Task', 'submit-fix-task', parsed); }}>提交 Fix Task</button></Panel>
    <Panel title="Review protocol details" className="span-all"><JsonView value={snapshot.reviews} /></Panel>
  </div>;
}
