import { useState } from 'react';
import { api } from '../api';
import { Badge, ErrorNotice, Field, JsonView, Panel, SuccessNotice, type PageProps } from '../components/Primitives';
import type { Project } from '../types';

export function SettingsPage({ projectId, snapshot, refresh, theme, setTheme, project, removeProject }: PageProps & { theme: string; setTheme: (theme: string) => void; project: Project; removeProject: () => Promise<void> }) {
  const [participant, setParticipant] = useState({ participantId: '', displayName: '', kind: 'agent', provider: '', adapterId: '', capabilities: '' });
  const [assignment, setAssignment] = useState({ assignmentId: '', role: 'worker', participantId: '', scopeType: 'room', scopeId: '' });
  const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  async function act(label: string, action: string, body: unknown) { setError(null); setSuccess(null); try { await api.action(projectId, action, body); setSuccess(`${label}已保存。`); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } }
  return <div className="page-grid"><ErrorNotice error={error} /><SuccessNotice message={success} />
    <Panel title="外观"><Field label="Theme"><select value={theme} onChange={(e) => setTheme(e.target.value)}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></Field></Panel>
    <Panel title="项目绑定" className="span-2"><JsonView value={project} /><button className="danger" onClick={() => void removeProject()}>仅移除 UI registry 绑定</button></Panel>
    <Panel title="注册 Participant" className="span-2"><div className="form-grid"><Field label="Participant ID"><input value={participant.participantId} onChange={(e) => setParticipant({ ...participant, participantId: e.target.value })} /></Field><Field label="Display name"><input value={participant.displayName} onChange={(e) => setParticipant({ ...participant, displayName: e.target.value })} /></Field><Field label="Kind"><select value={participant.kind} onChange={(e) => setParticipant({ ...participant, kind: e.target.value })}><option>human</option><option>agent</option><option>service</option></select></Field><Field label="Provider"><input value={participant.provider} onChange={(e) => setParticipant({ ...participant, provider: e.target.value })} /></Field><Field label="Adapter ID"><input value={participant.adapterId} onChange={(e) => setParticipant({ ...participant, adapterId: e.target.value })} /></Field><Field label="Capabilities（逗号分隔）"><input value={participant.capabilities} onChange={(e) => setParticipant({ ...participant, capabilities: e.target.value })} /></Field></div><button className="primary" onClick={() => void act('Participant', 'register-participant', { participant_id: participant.participantId, display_name: participant.displayName, kind: participant.kind, provider: participant.provider, adapter_id: participant.adapterId, capabilities: participant.capabilities.split(',').map((item) => item.trim()).filter(Boolean), config_ref: null, enabled: true })}>注册</button></Panel>
    <Panel title="RoleAssignment" className="span-2"><div className="form-grid"><Field label="Assignment ID"><input value={assignment.assignmentId} onChange={(e) => setAssignment({ ...assignment, assignmentId: e.target.value })} /></Field><Field label="Participant ID"><input value={assignment.participantId} onChange={(e) => setAssignment({ ...assignment, participantId: e.target.value })} /></Field><Field label="Role"><select value={assignment.role} onChange={(e) => setAssignment({ ...assignment, role: e.target.value })}>{['planner', 'worker', 'reviewer', 'executor', 'git_controller', 'orchestrator'].map((role) => <option key={role}>{role}</option>)}</select></Field><Field label="Scope"><select value={assignment.scopeType} onChange={(e) => setAssignment({ ...assignment, scopeType: e.target.value })}><option>room</option><option>plan</option><option>task</option></select></Field><Field label="Scope ID"><input value={assignment.scopeId} onChange={(e) => setAssignment({ ...assignment, scopeId: e.target.value })} disabled={assignment.scopeType === 'room'} /></Field></div><button className="primary" onClick={() => void act('RoleAssignment', 'create-role-assignment', { assignment_id: assignment.assignmentId, participant_id: assignment.participantId, role: assignment.role, scope_type: assignment.scopeType, scope_id: assignment.scopeType === 'room' ? null : assignment.scopeId })}>创建 assignment</button></Panel>
    <Panel title="Participants"><div className="list">{snapshot.participants.map((item) => <div className="list-row" key={String(item.participant_id)}><div><strong>{String(item.display_name)}</strong><p>{String(item.participant_id)} · {String(item.adapter_id)}</p></div><div className="button-row"><Badge tone={item.enabled ? 'good' : 'bad'}>{item.enabled ? 'enabled' : 'disabled'}</Badge><button onClick={() => void act('Participant state', 'set-participant-enabled', { participant_id: item.participant_id, enabled: !item.enabled })}>{item.enabled ? '禁用' : '启用'}</button></div></div>)}</div></Panel>
    <Panel title="Assignments" className="span-2"><JsonView value={snapshot.role_assignments} /></Panel>
  </div>;
}
